
package galeriadearte;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Clase implementada para controlar los artistas que participaran
 * en alguna exposición.
 */
public class ArtistasExposicion extends javax.swing.JFrame {

    private Conexion con;
    private ResultSet rsArtistas;
    private String sql;
    private int [] Artistas;
    private long codigoArtista;
    private long id;
    private int numArtistas;
    
    public ArtistasExposicion()
    {
    }
    
    /**
     * @param u Nombre del usuario
     * @param p Contraseña del usuario
     * @param id Codigo de la exposicion 
     */
    public ArtistasExposicion(String u, String p,long id) {
         
        initComponents();
       
        con = new Conexion(u, p, ArtistasExposicion,"select * from EXPOSICIONES.det_artistas_exposicion C where C.id_exposicion="+id);
        
        this.etIdExp.setText(Long.toString(id));
        this.setLocationRelativeTo(this);
        this.Artistas = new int[200];
        this.CargaArtistas();
        this.id=id;
    }

    /**
     * Este método se encarga de inicializar un control ComboBox con los nombres de los
     * artistas y a su vez guarda las clave primaria de cada uno de ellos en un arreglo.
     */
     public void CargaArtistas(){
        
        numArtistas = 0;
      
        try
        {
             con.EstableceConexion();
             rsArtistas = con.getSentencia().executeQuery("select A.Id_Artista, (A.Nombre||' '||A.Apellidos) AS Nombre from ARTISTAS.Artistas A");
    
             while(rsArtistas.next())
             {
               cbArtistas.addItem(rsArtistas.getObject(2));
               Artistas[numArtistas++] = Integer.parseInt( String.valueOf(rsArtistas.getObject(1)));
             }
             
             con.cierraConexion();
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdExposicion = new javax.swing.JLabel();
        cbArtistas = new javax.swing.JComboBox();
        NombreArtista = new javax.swing.JLabel();
        etIdExp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArtistasExposicion = new javax.swing.JTable();
        Salir1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Artistas en Exposicion");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        IdExposicion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdExposicion.setText("Id Exposición:");

        NombreArtista.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NombreArtista.setText("Artistas:");

        etIdExp.setBackground(new java.awt.Color(255, 102, 204));
        etIdExp.setText("#");

        ArtistasExposicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ArtistasExposicion);

        Salir1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Salir1.setText("Salir");
        Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuBar1.setDoubleBuffered(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(355, 60));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("    Agregar   ");
        jMenu1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("    Eliminar   ");
        jMenu3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IdExposicion)
                        .addGap(12, 12, 12)
                        .addComponent(etIdExp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(NombreArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdExposicion)
                    .addComponent(etIdExp)
                    .addComponent(NombreArtista)
                    .addComponent(cbArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        InsertArtExpo();
    }//GEN-LAST:event_jMenu1MouseClicked
    
    /**
     * Método para insertar un artistas en la exposicion
     */
    public void InsertArtExpo(){
        
        codigoArtista = Artistas[this.cbArtistas.getSelectedIndex()];
        sql = "insert into EXPOSICIONES.det_artistas_exposicion values ("+this.etIdExp.getText()+ ","+this.codigoArtista+ ");";
        con.setSQL(sql);
        con.setQueryTabla("select * from EXPOSICIONES.det_artistas_exposicion C where C.id_exposicion="+this.id);
        con.EjecutaSentencia();
    }
    
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        DeleteArtistaExp();
    }//GEN-LAST:event_jMenu3MouseClicked
    
    /**
     * Método para eleminar un artista en la exposición.
     */
    public void DeleteArtistaExp(){
        
        int opc;
        int fila=this.ArtistasExposicion.getSelectedRow();

        //Se obtiene el codigo de la exposición
        long idV=Long.parseLong(String.valueOf(this.ArtistasExposicion.getModel().getValueAt(fila, 1)));
        
        if(ArtistasExposicion.getSelectedRow() >= 0)
        {
            opc = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere eliminar el registro?", "Eliminación", JOptionPane.YES_NO_OPTION);
            if(opc == 0)
            {
                //Se define la consulta
                sql = "delete from EXPOSICIONES.det_artistas_exposicion where id_exposicion = "+this.etIdExp.getText()+"and id_Artista = "+idV ;
                con.setSQL(sql);
                con.setQueryTabla("select * from EXPOSICIONES.det_artistas_exposicion C where C.id_exposicion="+this.id);
                //Ejecución de la cosnulta
                con.EjecutaSentencia();
            }
        }else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro","Eliminación", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtistasExposicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtistasExposicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtistasExposicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtistasExposicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArtistasExposicion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ArtistasExposicion;
    private javax.swing.JLabel IdExposicion;
    private javax.swing.JLabel NombreArtista;
    private javax.swing.JButton Salir1;
    private javax.swing.JComboBox cbArtistas;
    private javax.swing.JLabel etIdExp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
