/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package galeriadearte;
import java.awt.Toolkit;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.freixas.jcalendar.JCalendarCombo;

/**
 * Autor: Miguel Angel Galicia Torrez 
 * Fecha de Inicio: 23 Marzo 2013
 * 
 * Esta clase es utilizada para gestionar los datos de los vendedores
 * cuenta con un conjunto de métodos que nos van a permitir operar la 
 * información de este.
 */
public class FVendedores extends FPersonas{
    
    private int [] fIngreso;
    private int [] fCreacion;
    private String fechaCreacionO;
    
    public FVendedores(){
        super();
    }
    
    /**
     * @param u Nombre del usuario
     * @param p Nombre de su contraseña
     */
    public FVendedores(String u, String p) {
        
        super(u,p,"select * from VENTAS.Vendedores");
        initComponents();
      
        this.fCreacion = new int[3];
        this.fIngreso = new int[3];
        
        this.ActualizaTabla(TablaVendedores);
        this.IniFechaIngreso();
        this.setLocationRelativeTo(this);
    }
    
     private void IniFechaIngreso(){
        
        JCalendarCombo cal = new JCalendarCombo();
        
        this.fIngreso = creaFecha(cal);
        this.FechaIncorporacion.setText(fIngreso[2]+"-"+fIngreso[1]+"-"+fIngreso[0]);
    }
    
    private void IniFechaCreacion(){
        
        this.fCreacion = creaFecha(FechaNacimiento);
        this.fechaCreacionO = fCreacion[2]+"-"+fCreacion[1]+"-"+fCreacion[0];
    }

     private int[] creaFecha(JCalendarCombo cal){
       
        Calendar  cl;
        int []date = new int[3];
        
        cl = cal.getCalendar();
        
        date[0]=cl.get(5); //Dia
        date[1]=cl.get(2)+1; //Mes
        date[2]=cl.get(1); //Año
        
        return(date);
    }
    
     private void Limpia(){
        
        this.IdVendedor.setText("#");
        this.Nombre.setText("");
        this.ApellidoPaterno.setText("");
        this.ApellidoMaterno.setText("");
        this.Direccion.setText("");
        this.CP.setText("");
        this.Ciudad.setText("");
        this.Telefono.setText("");
        this.Email.setText("");
        this.Porcentaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        TablaVendedores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        IdVendedor = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        ApellidoPaterno = new javax.swing.JTextField();
        ApellidoMaterno = new javax.swing.JTextField();
        FechaNacimiento = new org.freixas.jcalendar.JCalendarCombo();
        Direccion = new javax.swing.JTextField();
        CP = new javax.swing.JTextField();
        Ciudad = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Porcentaje = new javax.swing.JTextField();
        FechaIncorporacion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendedores");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Id Vendedor:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Fecha Nacimiento:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Dirección:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Ciudad:");

        C.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        C.setText("CP:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Fecha de Incorporación:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Porcentaje Comisión:");

        TablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaVendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVendedoresMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(TablaVendedores);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IdVendedor.setBackground(new java.awt.Color(255, 102, 204));
        IdVendedor.setText("1");

        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });

        ApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoPaternoKeyTyped(evt);
            }
        });

        ApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoMaternoKeyTyped(evt);
            }
        });

        CP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPKeyTyped(evt);
            }
        });

        Ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CiudadKeyTyped(evt);
            }
        });

        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeActionPerformed(evt);
            }
        });
        Porcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PorcentajeKeyTyped(evt);
            }
        });

        FechaIncorporacion.setBackground(new java.awt.Color(255, 102, 204));
        FechaIncorporacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FechaIncorporacion.setText("jLabel1");

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuBar1.setDoubleBuffered(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(355, 70));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galeriadearte/vendedor.png"))); // NOI18N
        jMenu1.setText("    Agregar   ");
        jMenu1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("    Eliminar   ");
        jMenu3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("    Modificar   ");
        jMenu4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galeriadearte/edit-clear.png"))); // NOI18N
        jMenu2.setText("Limpiar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(IdVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(C))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .addComponent(ApellidoMaterno)
                                            .addComponent(FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(Ciudad)))))
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IdVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(FechaIncorporacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C)
                    .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private int camposVacios(){
        
        int res = 0;
        
        if(this.Nombre.getText().trim().length() == 0 ||
           this.ApellidoPaterno.getText().trim().length() == 0 ||
           this.ApellidoMaterno.getText().trim().length() == 0 ||
           this.Direccion.getText().trim().length() == 0 ||
           this.CP.getText().trim().length() == 0 ||
           this.Ciudad.getText().trim().length() == 0 ||
           this.Telefono.getText().trim().length() == 0 ||
           this.Email.getText().trim().length() == 0 ||
           this.Porcentaje.getText().trim().length() == 0 )
        {
            res = 1;
        
        }
        
        return(res);
    }
    
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       InsertVendedor();
    }//GEN-LAST:event_jMenu1MouseClicked
    
    /**
     * Método para registrar un vendedor a la base de datos
     */
    public void InsertVendedor(){
        int dia, mes, anio;
        String fecha;

        dia  = FechaNacimiento.getCalendar().get(5);
        mes  = FechaNacimiento.getCalendar().get(2)+1;
        anio =FechaNacimiento.getCalendar().get(1);

        fecha = dia+"/"+mes+"/"+anio;
        
        //Validaciones previas al registro
        if(this.camposVacios() == 0)
        {
            if(this.validaFecha(anio)==1)
            {
                String s = this.Porcentaje.getText();
                int porcentaje = Integer.parseInt(s);

                //Se prepara la consulra DML para hacer la inserción del vendedor
                sql = "insert into VENTAS.Vendedores values (default,'"
                + this.Nombre.getText() + "','"
                + this.ApellidoPaterno.getText()+ "','"
                + this.ApellidoMaterno.getText()+ "','"
                + fecha+"','"
                + this.Direccion.getText()+"','"
                + this.Telefono.getText()+"','"
                + this.Ciudad.getText()+"','"
                + this.CP.getText()+"','"
                + this.Email.getText()+"','"
                + this.FechaIncorporacion.getText()+"','"
                + porcentaje+"');";

                EjecutaSentencia(TablaVendedores);
            }
             else
            {
                 JOptionPane.showMessageDialog(null, "La fecha de nacimiento debe ser anterior o igual al año 2000","Inserción", JOptionPane.ERROR_MESSAGE);
      
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "No puede haber campos vacios","Inserción", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private int validaFecha(int anio){
        int res=0;
        if(anio<=2000)
        {
            res=1;
        }
        return res;
    }
     
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        DeleteVendedor();
    }//GEN-LAST:event_jMenu3MouseClicked
    
    /**
     * Método para eleminar en vendedor de la base de datos
     */
    public void DeleteVendedor(){
        int opc;
        
        //Se verifica que se haya seleccionado el registro del vendedor
        if(TablaVendedores.getSelectedRow() >= 0)
        {
            opc = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere eliminar el registro?", "Eliminación", JOptionPane.YES_NO_OPTION);
            if(opc == 0)
            {
                sql = "delete from VENTAS.Vendedores where Id_Vendedor = "+this.IdVendedor.getText();
                EjecutaSentencia(TablaVendedores);
            }
        }else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro","Eliminación", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        UpdateVendedor();
    }//GEN-LAST:event_jMenu4MouseClicked
    
    /**
     * Método para actualizar los datos de un vendedor
     */
    public void UpdateVendedor(){
        int dia, mes, anio;
        String fecha;

        dia  = FechaNacimiento.getCalendar().get(5);
        mes  = FechaNacimiento.getCalendar().get(2)+1;
        anio =FechaNacimiento.getCalendar().get(1);

        fecha = dia+"/"+mes+"/"+anio;
        
        if(camposVacios() == 0)
        {
            sql = "update VENTAS.Vendedores set Id_Vendedor="
            + this.IdVendedor.getText()+",Nombre='"
            + this.Nombre.getText() + "',Apellido_Paterno='"
            + this.ApellidoPaterno.getText()+ "',Apellido_Materno='"
            + this.ApellidoMaterno.getText()+ "',Fecha_Nacimiento='"
            + fecha+"',Direccion='"
            + this.Direccion.getText()+"',Telefono='"
            + this.Telefono.getText()+"',Ciudad='"
            + this.Ciudad.getText()+"',CP='"
            + this.CP.getText()+"',Email='"
            + this.Email.getText()+"',Fecha_Incorporacion='"
            + this.FechaIncorporacion.getText()+"',Porcentaje_Comision='"
            + this.Porcentaje.getText()+"'"
            + "where Id_Vendedor ="+this.IdVendedor.getText();

            this.EjecutaSentencia(TablaVendedores);
        }else
        {
            JOptionPane.showMessageDialog(null, "No puede haber campos vacios","Inserción", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.Limpia();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorcentajeActionPerformed

    private void TablaVendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVendedoresMouseClicked
        // TODO add your handling code here:
         String fecha;
       
        
        int tuplaSel = TablaVendedores.getSelectedRow();
        this.IdVendedor.setText(String.valueOf(modelo.getValueAt(tuplaSel, 0)));
        this.Nombre.setText(String.valueOf(modelo.getValueAt(tuplaSel, 1)));
        this.ApellidoPaterno.setText(String.valueOf(modelo.getValueAt(tuplaSel, 2)));
        this.ApellidoMaterno.setText(String.valueOf(modelo.getValueAt(tuplaSel, 3)));
        this.fechaCreacionO = String.valueOf(modelo.getValueAt(tuplaSel, 4));
        this.FechaNacimiento.setDate(Date.valueOf(fechaCreacionO));
        this.Direccion.setText((String)modelo.getValueAt(tuplaSel, 5));
        this.Telefono.setText((String)modelo.getValueAt(tuplaSel, 6));
        this.Ciudad.setText((String)modelo.getValueAt(tuplaSel, 7));
        this.CP.setText((String)modelo.getValueAt(tuplaSel, 8));
        this.Email.setText((String)modelo.getValueAt(tuplaSel, 9));
        fecha = String.valueOf(modelo.getValueAt(tuplaSel, 10));
        this.FechaIncorporacion.setText(fecha);
        this.Porcentaje.setText((String.valueOf(modelo.getValueAt(tuplaSel, 11))));
       
    }//GEN-LAST:event_TablaVendedoresMouseClicked
    
    private void validaDigito(java.awt.event.KeyEvent evt, int l, JTextField t){
        
        if((t.getText().length() >= l) || (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())))
        {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }
   private void validaCadena(java.awt.event.KeyEvent evt){

        if(!Character.isSpaceChar(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) &&!Character.isLetter(evt.getKeyChar()))
        { 
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }
  
    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        validaCadena(evt);
    }//GEN-LAST:event_NombreKeyTyped

    private void ApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoPaternoKeyTyped
        validaCadena(evt);
    }//GEN-LAST:event_ApellidoPaternoKeyTyped

    private void ApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoMaternoKeyTyped
        validaCadena(evt);
    }//GEN-LAST:event_ApellidoMaternoKeyTyped
    
    private void CiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CiudadKeyTyped
       validaCadena(evt);
    }//GEN-LAST:event_CiudadKeyTyped

    private void CPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPKeyTyped
        validaDigito(evt, 5,CP);
    }//GEN-LAST:event_CPKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        validaDigito(evt,8,Telefono);
    }//GEN-LAST:event_TelefonoKeyTyped

    private void PorcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PorcentajeKeyTyped
       validaDigito(evt, 2,Porcentaje);
    }//GEN-LAST:event_PorcentajeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FVendedores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMaterno;
    private javax.swing.JTextField ApellidoPaterno;
    private javax.swing.JLabel C;
    private javax.swing.JTextField CP;
    private javax.swing.JTextField Ciudad;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel FechaIncorporacion;
    private org.freixas.jcalendar.JCalendarCombo FechaNacimiento;
    private javax.swing.JLabel IdVendedor;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Porcentaje;
    private javax.swing.JTable TablaVendedores;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane14;
    // End of variables declaration//GEN-END:variables
}
