
package galeriadearte;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * Autor: Miguel Angel Galicia Torrez 
 * Fecha de Inicio: 23 Marzo 2013
 * 
 * Esta clase es utilizada para gestionar los datos los clientes
 * cuenta con un conjunto de métodos que nos van a permitir operar la 
 * información de este.
 */
public class FClientes extends FPersonas {

    public FClientes(){
        super();
    }
    
    /**
     * @param u Nombre del usuario
     * @param p Contraseña del usuario
     */
    public FClientes(String u, String p) {
        
        super(u,p,"select * from VENTAS.Clientes");
        initComponents();
 
        this.setLocationRelativeTo(this);
        this.ActualizaTabla(TablaClientes);
        this.Limpia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        IdCliente = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        ApellidoPaterno = new javax.swing.JTextField();
        ApellidoMaterno = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        CP = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Ciudad = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Id Cliente:");

        C.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        C.setText("CP:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Dirección:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Ciudad:");

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientesMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(TablaClientes);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IdCliente.setBackground(new java.awt.Color(255, 102, 204));
        IdCliente.setText("1");

        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });

        ApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoPaternoKeyTyped(evt);
            }
        });

        ApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoMaternoKeyTyped(evt);
            }
        });

        CP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CPKeyTyped(evt);
            }
        });

        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        Ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CiudadKeyTyped(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuBar1.setDoubleBuffered(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(355, 60));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galeriadearte/clients.png"))); // NOI18N
        jMenu1.setText("    Agregar   ");
        jMenu1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("    Eliminar   ");
        jMenu3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("    Modificar   ");
        jMenu4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galeriadearte/edit-clear.png"))); // NOI18N
        jMenu2.setText("Limpiar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(C)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdCliente)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C)
                    .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Limpia(){
        
        this.IdCliente.setText("#");
        this.Nombre.setText("");
        this.ApellidoPaterno.setText("");
        this.ApellidoMaterno.setText("");
        this.Direccion.setText("");
        this.CP.setText("");
        this.Telefono.setText("");
        this.Ciudad.setText("");
        this.Email.setText("");
    }
    
    private int camposVacios(){
        
        int res = 0;
        
        if(this.Nombre.getText().trim().length() == 0 ||
           this.ApellidoPaterno.getText().trim().length() == 0 ||
           this.ApellidoMaterno.getText().trim().length() == 0 ||
           this.Direccion.getText().trim().length() == 0 ||
           this.CP.getText().trim().length() == 0 ||
           this.Telefono.getText().trim().length() == 0 ||
           this.Ciudad.getText().trim().length() == 0 ||
           this.Email.getText().trim().length() == 0)
           res = 1;
        
        return(res);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        InsertClient();
    }//GEN-LAST:event_jMenu1MouseClicked
    
    /**
     * Método para insertar un cliente a la base de datos.
     */
    public void InsertClient(){
       
        if(this.camposVacios() == 0)
        {
            //Se prepara la sentencia DML para insertar un cliente a la base de datos
            sql = "insert into VENTAS.Clientes values (default,'"
            + this.Nombre.getText() + "','"
            + this.ApellidoPaterno.getText()+ "','"
            + this.ApellidoMaterno.getText()+"','"
            + this.Direccion.getText()+"','"
            + this.Telefono.getText()+"','"
            + this.Ciudad.getText()+"','"
            + this.CP.getText()+"','"
            + this.Email.getText()+"');";
            
            //Se ejecuta la consulta
            EjecutaSentencia(TablaClientes);
        }else
        {
            JOptionPane.showMessageDialog(null, "No puede haber campos vacios","Inserción", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        DeleteClient();
    }//GEN-LAST:event_jMenu3MouseClicked
    
    /**
     * Método para dar de baja un cliente de la base de datos
     */
    public void DeleteClient(){
        int opc;
        
        //Se checa que se haya seleccionado un registro de algun cliente.
        if(TablaClientes.getSelectedRow() >= 0)
        {
            opc = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere eliminar el registro?", "Eliminación", JOptionPane.YES_NO_OPTION);
            if(opc == 0)
            {
                //Se prepara la consulta de eleminación y despues es ejecutada
                sql = "delete from VENTAS.Clientes where Id_Cliente = "+this.IdCliente.getText();
                EjecutaSentencia(TablaClientes);
            }
        }else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro","Eliminación", JOptionPane.ERROR_MESSAGE);
        }
    }    
    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        UpdateClient();
    }//GEN-LAST:event_jMenu4MouseClicked
    
    /**
     * Método para actualizar los datos de un cliente
     */
    public void UpdateClient(){
       
        if(this.camposVacios() == 0)
        {
            //Consulta DML para modificar los datos de algun cliente            
            sql = "update VENTAS.Clientes set Id_Cliente="
            + this.IdCliente.getText()+",Nombre='"
            + this.Nombre.getText() + "',Apellido_Paterno='"
            + this.ApellidoPaterno.getText()+ "',Apellido_Materno='"
            + this.ApellidoMaterno.getText()+"',Direccion='"
            + this.Direccion.getText()+"',Telefono='"
            + this.Telefono.getText()+"',Ciudad='"
            + this.Ciudad.getText()+"',CP='"
            + this.CP.getText()+"',Email='"
            + this.Email.getText()+"'"
            + "where Id_Cliente ="+this.IdCliente.getText();

            EjecutaSentencia(TablaClientes);
        }else
        {
            JOptionPane.showMessageDialog(null, "No puede haber campos vacios","Inserción", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.Limpia();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void TablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientesMouseClicked
        // TODO add your handling code here:
         String fecha;
        int tuplaSel = TablaClientes.getSelectedRow();

        this.IdCliente.setText( String.valueOf(modelo.getValueAt(tuplaSel, 0)));
        this.Nombre.setText((String)modelo.getValueAt(tuplaSel, 1));
        this.ApellidoPaterno.setText((String)modelo.getValueAt(tuplaSel, 2));
        this.ApellidoMaterno.setText((String)modelo.getValueAt(tuplaSel, 3));
        this.Direccion.setText((String)modelo.getValueAt(tuplaSel, 4));
        this.Telefono.setText((String)modelo.getValueAt(tuplaSel, 5));
        this.Ciudad.setText((String)modelo.getValueAt(tuplaSel, 6));
        this.CP.setText((String)modelo.getValueAt(tuplaSel, 7));
        this.Email.setText((String)modelo.getValueAt(tuplaSel, 8));
       
    }//GEN-LAST:event_TablaClientesMouseClicked

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        validaCadena(evt);
    }//GEN-LAST:event_NombreKeyTyped

    private void ApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoPaternoKeyTyped
        validaCadena(evt);
    }//GEN-LAST:event_ApellidoPaternoKeyTyped

    private void ApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoMaternoKeyTyped
       validaCadena(evt);
    }//GEN-LAST:event_ApellidoMaternoKeyTyped

    private void CiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CiudadKeyTyped
        validaCadena(evt);
    }//GEN-LAST:event_CiudadKeyTyped

    private void CPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CPKeyTyped
        if((CP.getText().length() >= 5) || (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())))
        {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_CPKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        if((Telefono.getText().length() >= 8) || (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())))
        {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void validaCadena(java.awt.event.KeyEvent evt){

        if(!Character.isSpaceChar(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) &&!Character.isLetter(evt.getKeyChar()))
        { 
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
     }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FClientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMaterno;
    private javax.swing.JTextField ApellidoPaterno;
    private javax.swing.JLabel C;
    private javax.swing.JTextField CP;
    private javax.swing.JTextField Ciudad;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel IdCliente;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane13;
    // End of variables declaration//GEN-END:variables
}
