/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package galeriadearte;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Clase encargada de agregar los vendedores que participaran en alguna exposición
 */
public class VendedoresExposicion extends javax.swing.JFrame {

    private Conexion con;
    private ResultSet rsArtistas;
    private int [] Vendedores;
    private long codigoArtista;
    private int numArtistas;
    private String sql;
    private String u;
    private String p;
    private long id;
    
    
    public VendedoresExposicion() {
        
    }
    
    /**
     * @param u Nombre del usuario
     * @param p Contraseña del usuario
     * @param id  Clave primaria de la exposición
     */
    public VendedoresExposicion(String u, String p,long id) {
        initComponents();
        
        con = new Conexion(u, p, VendedoresExposicion, "select * from VENTAS.comisionesporexposicion C where C.codigo_exposicion="+ id);
        
        this.etIdExp.setText(Long.toString(id));
        this.setLocationRelativeTo(this);
        this.Vendedores = new int[200];
        this.CargaVendedores();
        this.id=id;
    }
    
    /**
     * Este método se encarga de cargar los nombres de los vendedores en un comboBox y a su vez su llave
     * primaria almacenandola en un arreglo
     */
    public void CargaVendedores(){
        
        this.numArtistas = 0;
        
        try
        {
             con.EstableceConexion();
             rsArtistas = con.getSentencia().executeQuery("select V.Id_Vendedor, (V.Nombre||' '||V.Apellido_Paterno) AS Nombre  from VENTAS.Vendedores V");
    
             while(rsArtistas.next())
             {
               cbVendedores.addItem(rsArtistas.getObject(2));
               Vendedores[numArtistas++] = Integer.parseInt( String.valueOf(rsArtistas.getObject(1)));
             }
             
             con.cierraConexion();
             
        }catch(Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdExposicion = new javax.swing.JLabel();
        NombreVendedor = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VendedoresExposicion = new javax.swing.JTable();
        etIdExp = new javax.swing.JLabel();
        cbVendedores = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendedores en Exposición");

        IdExposicion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdExposicion.setText("Id Exposición:");

        NombreVendedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NombreVendedor.setText("Vendedores:");

        Salir.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        VendedoresExposicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(VendedoresExposicion);

        etIdExp.setBackground(new java.awt.Color(255, 102, 204));
        etIdExp.setText("#");

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuBar1.setDoubleBuffered(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(355, 60));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("    Agregar   ");
        jMenu1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("    Eliminar   ");
        jMenu3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(IdExposicion)
                            .addGap(12, 12, 12)
                            .addComponent(etIdExp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(NombreVendedor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdExposicion)
                    .addComponent(etIdExp)
                    .addComponent(cbVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreVendedor))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salir)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        InsertVendedorExp();
    }//GEN-LAST:event_jMenu1MouseClicked
    
    /**
     * Método para insertar un vendedor en la exposición en forma fisica y logica
     */
    public void InsertVendedorExp(){
        codigoArtista = Vendedores[this.cbVendedores.getSelectedIndex()];   
                sql = "insert into VENTAS.comisionesporexposicion values ("
                        +this.etIdExp.getText()+ ",'"
                        + this.codigoArtista+ "',"
                        + 0+","
                        + 0+");";
                con.setSQL(sql);
                con.setQueryTabla("select * from VENTAS.comisionesporexposicion C where C.codigo_exposicion="+this.id);
                con.EjecutaSentencia();
    }
    
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        DeleteVendedorExp();
    }//GEN-LAST:event_jMenu3MouseClicked
    
    /**
     * Método para eleminar un vendedor en alguna exposición. La eleminación es de manera 
     * fisica y lógica.
     */
    public void DeleteVendedorExp(){
        int opc;
        int fila=this.VendedoresExposicion.getSelectedRow();
        
        //Se obtiene la llave primaria de la exposición.
        long idV=Long.parseLong(String.valueOf(this.VendedoresExposicion.getModel().getValueAt(fila, 1)));
        
        if(VendedoresExposicion.getSelectedRow() >= 0)
        {
            opc = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere eliminar el registro?", "Eliminación", JOptionPane.YES_NO_OPTION);
            if(opc == 0)
            {
                sql = "delete from VENTAS.comisionesporexposicion where codigo_exposicion = "+this.etIdExp.getText()
                       + "and codigo_vendedor = "+idV ;
                con.setSQL(sql);
                con.setQueryTabla("select * from VENTAS.comisionesporexposicion C where C.codigo_exposicion="+this.id);
                con.EjecutaSentencia();
            }
        }else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro","Eliminación", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendedoresExposicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendedoresExposicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendedoresExposicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendedoresExposicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendedoresExposicion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdExposicion;
    private javax.swing.JLabel NombreVendedor;
    private javax.swing.JButton Salir;
    private javax.swing.JTable VendedoresExposicion;
    private javax.swing.JComboBox cbVendedores;
    private javax.swing.JLabel etIdExp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
